### PR TITLE
Implement getting all participant in a room

### LINKED ISSUE #100: Implement getting all participant in a room

### PR DESCRIPTION
**Pull request by Mojtabarezaei4**
close #100

### CODE REVIEW

**Review by FabianAronsson — COMMENTED** [review]
What will this method be used for?

**Comment by Mojtabarezaei4** [comment]
Though to fetching all participants in a certain room. But maybe we accomplish this by just getting a room?

**Comment by FabianAronsson** [comment]
> Though to fetching all participants in a certain room. But maybe we accomplish this by just getting a room?

At the moment I think just getting the entire room whenever you load the room is the way to go. We will use SignalR regardless so the state is preserved for all the users who are currently connected to the room. We of course save the state whenever someone updates their status, but that is only loaded on the initial load, which means we will load the entire room anyway.

**Comment by Mojtabarezaei4** [comment]
Yeah off course. I just didn't think through enough,

**Pull request closed without merging**
