### PR TITLE
Create data models

### LINKED ISSUE #6: Create data models

### PR DESCRIPTION
**Pull request by FabianAronsson**
Closes #6 by adding the models as specified on the planning wiki. 

The models can later be used in the repositories. 

Also, in EF you do not use 
```csharp
[Id]
```
you use
```csharp
[Key]
```

### CODE REVIEW

**Review by Mojtabarezaei4 — APPROVED** [review]

**Comment by Mojtabarezaei4** [comment]
Some merge conflicts need to get fixed

**Review by Mojtabarezaei4 — CHANGES_REQUESTED** [review]
Merge conflicts

**Comment by FabianAronsson** [comment]
@Mojtabarezaei4 merge conflicts resolved

**Review by FabianAronsson — COMMENTED** [review]
Resolved

**Review by Mojtabarezaei4 — APPROVED** [review]

**Pull request merged**
