### PR TITLE
Add hashids

### LINKED ISSUE #29: Add support for HashIds
https://github.com/psypanda/hashID

### PR DESCRIPTION
**Pull request by FabianAronsson**
Adds support for hashids. We have to change our datamodel ids to ints, otherwise this package will not work.

Closes #29

### CODE REVIEW

**Comment by Mojtabarezaei4** [comment]
Why does it have to be int?
HashIds should not be stored in db

**Comment by FabianAronsson** [comment]
@Mojtabarezaei4 the hashids are not stored in the database. The package https://hashids.org/net/ does not support encoding strings or Guids, which means our room ids has to be ints. 

When you encode something using the hashid package you use a salt which is a string and a number as input. The output is a string and we send this in the handler back to the client for use. When a user wants to connect from the client they send a room id in the form of our hashid which we decode to a int and compare it with our database and grant access to the user if it is a valid id.

**Review by Mojtabarezaei4 — APPROVED** [review]
All right! Good call.

Do you update the changes on Wiki as well?

**Comment by FabianAronsson** [comment]
Yes I will change it

**Pull request merged**
